### ISSUE TITLE
Aliasing console methods does not work in WebKit

### ISSUE THREAD

**Issue by pcheese** [padolsey-archive/jquery.lint--old#3]
jQuery Lint breaks in Safari and Chrome (at least on a Mac).

See [this StackOverflow post](http://stackoverflow.com/questions/2089954/using-native-code-functions-as-javascript-objects-in-webkit) for details.

Here is a workaround (include this after the jquery.lint.js script tag):

```
if((jQuery.browser.safari || jQuery.browser.webkit) && window.console) {
    jQuery.LINT.level = 3;
    jQuery.LINT.console = {
        warn: function() { console.warn.apply(console, arguments); },
        group: function() { console.group.apply(console, arguments); },
        groupEnd: function() { console.groupEnd(); },
        groupCollapsed: function() { console.group.apply(console, arguments); },
        log: function() { console.log.apply(console, arguments); }
    }
}
```

**Comment by padolsey** [comment]
Thanks for reporting this. Fixed it - http://github.com/jamespadolsey/jQuery-Lint/commit/8e4d4b478b1293a8ad7486842dcb23b4f3aa91b1

Oddly, Firebug (the latest version) is fine with aliasing console's methods.
