### ISSUE TITLE
additional tests

### ISSUE THREAD

**Issue by paulirish** [padolsey-archive/jquery.lint--old#4]
- incorrect selector filters.. like `$('input:active')`
- $().ready

these would require different techniques.. maybe a **defineGetter**
- $.browser.safari is deprecated
- jQuery.boxModel is deprecated

**Comment by padolsey** [comment]
Thanks Paul!

I added all of these, although, as you know, the `$.browser/boxModel` checks will only work with JS engines that allow `__defineGetter__` ...

See the commit: http://github.com/jamespadolsey/jQuery-Lint/commit/b406451a15eeda27cf0c67874053e0242bde9b09
