### ISSUE TITLE
jQuery.extend(nonPlainObject, nonPlainObject) raises misuse report

### ISSUE THREAD

**Issue by padolsey** [padolsey-archive/jquery.lint--old#6]
The jQuery API specifies that the `jQuery.extend` function accepts the following argument signatures:

```
jQuery.extend(target, [object1], [objectN])
jQuery.extend([deep], target, object1, [objectN])
```

`object1`, `objectN` and `target` all have the type `Object`. And so, with Lint, we're checking that each of them is an object with the following check:

```
Object.prototype.toString.call(thing) === '[object Object]';
```

More advanced users are likely to want to use `extend` for other things. E.g.

```
jQuery.extend(
    function(){
        // A constructor
    },
    {
        prototype: {
            // Methods
        }
    }
)
```

This throws a misuse report, as you would expect, given the mentioned signatures.

I think, possibly, this kind of usage should be allowed, but I need some feedback before I move forward with it. Any thoughts welcome.

If changed, it would allow any type of object (except primitives) as the `target`, `object` and `objectN`.

**Comment by slubowsky** [comment]
While I dont yet consider myself an advanced user, I want to do something simple like
var newObject = $.extend({}, originalObject);
to get a shallow copy which I think is accepted usage and its reporting a misuse

**Comment by strayer** [comment]
Actually... jQuery UI does this:

<pre>
$.extend($.ui.draggable, {
    version: "1.8.2"
});
</pre>

( $.ui.draggable is a function )

This is really annoying in my current project because lint always logs around 7 "... called incorrectly" entries in my console.

**Comment by padolsey** [comment]
I've added `extend( [function], [object] ...)` as a signature in the new version of jQ lint. Download it and try it out pls. - http://github.com/jamespadolsey/jQuery-Lint/blob/master/jquery.lint.js

**Comment by strayer** [comment]
Thanks for the fast response! These warnings are gone now.

Two other warnings still remain:

<pre>
No elements were found with the selector: ".ui-dialog-buttonpane"
No elements were found with the selector: "*"
</pre>

But I guess these are bugs in jquery ui.
