### ISSUE TITLE
Not compatable with qTip

### ISSUE THREAD

**Issue by ghost** [padolsey-archive/jquery.lint--old#7]
Tried including jQuery-lint in a project that uses qTip (http://craigsworks.com/projects/qtip/). Getting:

When I called jQuery.each(...) with your args, an error was thrown! TypeError: $.fn.qtip.styles is undefined { message="$.fn.qtip.styles is undefined",  more...}

As far as I can tell, it's defined in the plugin. This is with jQuery 1.3.2, same results whether I use the minified or development version of qTip.

**Comment by padolsey** [comment]
Thanks for raising this. I've committed a fix: http://github.com/jamespadolsey/jQuery-Lint/commit/36e9dd1bbd796d6d07ce4501d56b8145114fae72

The latest version of jQuery Lint should work with qTip now :)
